(defpackage raytracer/tests/matrices
  (:use :cl
        :raytracer
        :3d-vectors
        :3d-matrices
        :rove)
  (:import-from :raytracer
                #:approximately
                #:default-plane
                #:default-sphere
                #:default-world
                #:point
                #:vectorr))
(defpackage raytracer/tests/rays
  (:use :cl
        :raytracer
        :3d-vectors
        :3d-matrices
        :rove)
  (:import-from :raytracer
     #:approximately
     #:camera-pixel-size
     #:color
     #:color-at
     #:computations-eyev
     #:computations-inside
     #:computations-n1
     #:computations-n2
     #:computations-normalv
     #:computations-object
     #:computations-over-point
     #:computations-point
     #:computations-reflectv
     #:computations-tt
     #:computations-under-point
     #:default-cube
     #:default-plane
     #:default-sphere
     #:default-world
     #:glass-sphere
     #:hit
     #:+identity-matrix+
     #:intersect
     #:intersect-world
     #:intersektion-object
     #:intersektion-tt
     #:is-shadowed
     #:lighting
     #:make-gradient-pattern
     #:make-intersektion
     #:make-light
     #:make-material
     #:make-ray
     #:make-ring-pattern
     #:make-sphere
     #:make-stripe-pattern
     #:make-test-pattern
     #:make-world
     #:material-ambient
     #:material-colour
     #:material-diffuse
     #:material-pattern
     #:material-shininess
     #:material-specular
     #:normal-at
     #:pattern-at
     #:pattern-at-shape
     #:pixel-at
     #:point
     #:prepare-computations
     #:ray-direction
     #:ray-for-pixel
     #:ray-origin
     #:ray-position
     #:reflect
     #:reflected-color
     #:refracted-color
     #:schlick
     #:shade-hit
     #:shape-material
     #:transform
     #:vectorr
     #:world-light
     #:world-shapes))
