(defpackage #:raytracer
  (:export
     #:approximately
     #:cofactor
     #:color
     #:color-at
     #:computations-eyev
     #:computations-inside
     #:computations-normalv
     #:computations-object
     #:computations-point
     #:computations-tt
     #:default-world 
     #:determinant
     #:draw
     #:hit
     #:*identity-matrix*
     #:intersect
     #:intersect-world
     #:intersektion-object
     #:intersektion-tt
     #:inverse
     #:light-intensity
     #:light-position
     #:lighting
     #:make-intersektion
     #:make-light
     #:make-material
     #:make-ray
     #:make-sphere
     #:make-world
     #:material-ambient
     #:material-colour
     #:material-diffuse
     #:material-shininess
     #:material-specular
     #:minor
     #:mm
     #:normal-at
     #:point
     #:prepare-computations
     #:ray-direction
     #:ray-origin
     #:ray-position
     #:reflect
     #:rotation-x
     #:rotation-y
     #:rotation-z
     #:scaling
     #:shade-hit
     #:shearing
     #:sphere-material 
     #:sphere-transform
     #:submatrix
     #:transform
     #:translation
     #:vectorr
     #:view-transform
     #:world-light
     #:world-shapes
     )
  (:use #:cl))
