(defpackage raytracer
  (:use :cl :3d-vectors :3d-matrices )
  (:export
     #:+black+
     #:+white+
     #:+green+
     #:+lime+
     #:+red+
     #:+yellow+
     #:+pink+
     #:+orange+
     #:+blue+
     #:approximately
     #:camera-pixel-size
     #:camera-transform
     #:cofactor
     #:color
     #:color-at
     #:computations-eyev
     #:computations-inside
     #:computations-normalv
     #:computations-object
     #:computations-over-point 
     #:computations-point
     #:computations-tt
     #:create-camera
     #:default-plane
     #:default-sphere
     #:default-world
     #:draw
     #:+epsilon+
     #:hit
     #:+identity-matrix+
     #:intersect
     #:intersect-world
     #:intersektion-object
     #:intersektion-tt
     #:minv
     #:is-shadowed
     #:light-intensity
     #:light-position
     #:lighting
     #:make-checkers-pattern
     #:make-gradient-pattern
     #:make-intersektion
     #:make-light
     #:make-material
     #:make-plane
     #:make-ray
     #:make-ring-pattern
     #:make-sphere
     #:make-stripe-pattern
     #:make-world
     #:material-ambient
     #:material-colour
     #:material-diffuse
     #:material-pattern 
     #:material-shininess
     #:material-specular
     #:minor
     #:m*
     #:normal-at
     #:pixel-at
     #:pattern-at 
     #:point
     #:prepare-computations
     #:ray-direction
     #:ray-for-pixel
     #:ray-origin
     #:ray-position
     #:reflect
     #:render
     #:rotation-x
     #:rotation-y
     #:rotation-z
     #:save-canvas
     #:scaling
     #:shade-hit
     #:shearing
     #:shape-material 
     #:shape-transform
     #:sphere
     #:submatrix
     #:transform
     #:translation
     #:vectorr
     #:mlookat
     #:world-light
     #:world-shapes
     )
  )
